Add kubebuilder markers for resource path and shortname
migtools/oadp-non-admin pull request #63
Opened 2024-05-09 18:45 UTC by shubham-pampattiwar

2024-05-09 18:53 UTC, kaovilai approved these changes

2024-05-10 14:11 UTC, mateusoliveira43 requested changes
No PR description

Please add motivation and how to test

2024-05-13 18:19 UTC, shubham-pampattiwar commented
@mateusoliveira43 I have updated the PR description PTAL, Thanks !

2024-05-13 19:05 UTC, mateusoliveira43 approved these changes
tested running
```
./bin/kustomize-v5.3.0 build config/crd | oc apply -f -
oc get nab
./bin/kustomize-v5.3.0 build config/crd | oc delete -f -
```
in this branch and master. In master, it errors out `error: the server doesn't have a resource type "nab"` and in the PR branch it works `No resources found in default namespace.`.
/lgtm

2024-05-13 19:08 UTC, merged